CREATE TABLE tasks (
    id VARCHAR(255) SERIAL UNIQUE PRIMARY KEY,
    user_email VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
)
CREATE TABLE user (
    id VARCHAR(255) PRIMARY KEY,
	user_name VARCHAR(255) NOT NULL
    user_email VARCHAR(255) UNIQUE NOT NULL
)